services:
  camera_handler:
    build:
      context: .
      dockerfile: Dockerfile.jetson
    container_name: camera-handler
    network_mode: host
    restart: unless-stopped

    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
      - CUDA_LAUNCH_BLOCKING=1
    privileged: true
    volumes:
      - /home/jetson/ros2_ws/images:/ros2_ws/images # You path
      - /home/jetson/ros2_ws/src/iiwa_realsense_camera/models:/ros2_ws/include/share/iiwa_realsense_camera/models
    devices:
      # RealSense D400
      - "/dev/video0:/dev/video0"
      - "/dev/video1:/dev/video1"
      - "/dev/video2:/dev/video2"
      - "/dev/video3:/dev/video3"
      - "/dev/video4:/dev/video4"
      - "/dev/video5:/dev/video5"
      # RealSense L500
      - "/dev/video5:/dev/video6"
      - "/dev/video5:/dev/video7"

      - "/dev/HID-SENSOR-2000e1.4.auto:/dev/HID-SENSOR-2000e1.4.auto"
      # Jetson DLA (optional)
      # - "/dev/nvhost-dla:/dev/nvhost-dla"
